# Generated by Django 2.2 on 2019-04-25 20:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Username')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=30, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('suffix', models.CharField(blank=True, max_length=10, null=True, verbose_name='Suffix')),
                ('studentnum', models.PositiveIntegerField(null=True, verbose_name='Student Number')),
                ('email', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('course', models.CharField(max_length=60, verbose_name='Course/Degree Program')),
                ('admin_status', models.BooleanField(default=False, verbose_name='Is Administrator?')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='Experience Points')),
                ('prof_pic', models.CharField(max_length=100, verbose_name='Profile Pic URL')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=140)),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Course Name')),
                ('code', models.CharField(max_length=10, verbose_name='Course Code')),
                ('number', models.CharField(max_length=10, verbose_name='Course Number')),
                ('title', models.CharField(max_length=50, verbose_name='Course Title')),
                ('description', models.TextField(blank=True, verbose_name='Course Description')),
                ('old_curr', models.BooleanField(default=False, verbose_name='Pre-2018 Curriculum Exclusive?')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible?')),
                ('lastupdated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated')),
                ('coreqs', models.ManyToManyField(blank=True, default=None, related_name='_course_coreqs_+', to='reviewer.Course')),
                ('prereqs', models.ManyToManyField(blank=True, default=None, related_name='_course_prereqs_+', to='reviewer.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False, verbose_name='Verified?')),
                ('verifier', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Course')),
                ('ex_lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewer.Language')),
                ('prereq_lesson', models.ManyToManyField(blank=True, default=None, related_name='_lesson_prereq_lesson_+', to='reviewer.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=140)),
                ('image_url', models.CharField(max_length=100)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Comment')),
                ('user_attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_code', models.TextField()),
                ('qtype', models.CharField(max_length=50)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('custom_code', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='course_attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('datepost', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='importuser',
            name='fave_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewer.Language'),
        ),
        migrations.AddField(
            model_name='importuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='importuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
