# Generated by Django 2.2 on 2019-04-23 23:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=140)),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Course Name')),
                ('code', models.CharField(max_length=10, verbose_name='Course Code')),
                ('number', models.CharField(max_length=10, verbose_name='Course Number')),
                ('title', models.CharField(max_length=50, verbose_name='Course Title')),
                ('description', models.TextField(blank=True, verbose_name='Course Description')),
                ('old_curr', models.BooleanField(default=False, verbose_name='Pre-2018 Curriculum Exclusive?')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible?')),
                ('lastupdated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated')),
                ('coreqs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_coreqs', to='reviewer.Course')),
                ('prereqs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_prereqs', to='reviewer.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Username')),
                ('firstname', models.CharField(max_length=30, verbose_name='First Name')),
                ('middlename', models.CharField(max_length=30, verbose_name='Middle Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='Suffix')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('studentnum', models.PositiveIntegerField(verbose_name='Student Number')),
                ('email', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('course', models.CharField(max_length=60, verbose_name='Course/Degree Program')),
                ('admin_status', models.BooleanField(default=False, verbose_name='Is Administrator?')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='Experience Points')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=140)),
                ('image_url', models.CharField(max_length=100)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Comment')),
                ('user_attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.User')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_code', models.TextField()),
                ('qtype', models.CharField(max_length=50)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('custom_code', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='course_attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.Course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.User'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('datepost', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.User')),
            ],
        ),
    ]
