# Generated by Django 3.0.4 on 2020-03-18 11:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
