# Generated by Django 2.2 on 2019-04-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importuser',
            name='admin_status',
        ),
        migrations.AlterField(
            model_name='importuser',
            name='fave_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewer.Language', verbose_name='Favorite Language'),
        ),
        migrations.AlterField(
            model_name='importuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Is SuperUser?'),
        ),
        migrations.AlterField(
            model_name='importuser',
            name='prof_pic',
            field=models.FileField(upload_to='', verbose_name='Profile Picture'),
        ),
    ]
