# Generated by Django 3.0.4 on 2020-04-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='imageID',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Photo ID'),
        ),
    ]
