# Generated by Django 2.2 on 2019-04-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible?'),
        ),
    ]
