# Generated by Django 2.2 on 2019-04-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coreqs',
        ),
        migrations.AddField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, default=None, related_name='_course_coreqs_+', to='reviewer.Course'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='prereqs',
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, default=None, related_name='_course_prereqs_+', to='reviewer.Course'),
        ),
    ]
