# Generated by Django 3.0.5 on 2020-04-13 09:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='module_code',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module_content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='custom_code',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
