# Generated by Django 2.2 on 2019-04-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20190424_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='prereq_lesson',
            field=models.ManyToManyField(blank=True, default=None, related_name='_lesson_prereq_lesson_+', to='reviewer.Lesson'),
        ),
    ]
