# Generated by Django 3.0.5 on 2020-04-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20200413_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
