# Generated by Django 2.2 on 2019-04-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20190426_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='image_url',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='importuser',
            name='prof_pic',
            field=models.FileField(null=True, upload_to='', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Icon'),
        ),
    ]
