# Generated by Django 3.0.4 on 2020-03-19 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reviewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20200318_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=reviewer.models.announcement_uploadto, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
