# Generated by Django 3.0.5 on 2020-04-21 19:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20200421_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='module_code',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='module_content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='prereq_lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='rel_lesson',
            field=models.ManyToManyField(blank=True, default=None, related_name='_lesson_rel_lesson_+', to='reviewer.Lesson'),
        ),
        migrations.AddField(
            model_name='question',
            name='module_code',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='module_content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
