# Generated by Django 3.0.4 on 2020-04-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20200404_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
