# Generated by Django 3.0.3 on 2020-03-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_lessonstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='color',
            field=models.CharField(default='868686', max_length=6),
        ),
    ]
