# Generated by Django 2.2 on 2019-04-25 22:18

from django.db import migrations, models
import reviewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_auto_20190426_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.FileField(null=True, upload_to=reviewer.models.post_uploadto, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='importuser',
            name='prof_pic',
            field=models.FileField(blank=True, null=True, upload_to=reviewer.models.user_uploadto, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.FileField(upload_to=reviewer.models.language_uploadto, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='image',
            field=models.FileField(null=True, upload_to=reviewer.models.post_uploadto, verbose_name='Image'),
        ),
    ]
