# Generated by Django 2.2 on 2019-04-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_auto_20190426_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_len',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
