# Generated by Django 3.0.5 on 2020-04-28 23:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_auto_20200428_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='custom_code',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
