# Generated by Django 2.2 on 2019-04-26 01:46

from django.db import migrations, models
import reviewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_course_number_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=reviewer.models.post_uploadto, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=reviewer.models.post_uploadto, verbose_name='Image'),
        ),
    ]
