# Generated by Django 2.2 on 2019-04-26 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_auto_20190426_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted'),
        ),
        migrations.AddField(
            model_name='reply',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted'),
        ),
    ]
