# Generated by Django 2.2 on 2019-04-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0007_auto_20190426_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, default=None, related_name='creq', to='reviewer.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, default=None, related_name='preq', to='reviewer.Course'),
        ),
    ]
