# Generated by Django 2.2.4 on 2019-09-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0010_auto_20190427_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='importuser',
            name='show_email',
            field=models.BooleanField(default=True, verbose_name='Show E-mail'),
        ),
        migrations.AddField(
            model_name='importuser',
            name='show_studentnum',
            field=models.BooleanField(default=True, verbose_name='Show Student Number'),
        ),
    ]
