# Generated by Django 2.2.4 on 2019-09-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0012_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='importuser',
            name='dark_mode',
            field=models.BooleanField(default=True, verbose_name='Dark Mode'),
        ),
    ]
