# Generated by Django 2.2.4 on 2019-09-18 07:05

from django.db import migrations, models
import reviewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0013_importuser_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=reviewer.models.course_uploadto, verbose_name='Cover Photo'),
        ),
        migrations.AlterField(
            model_name='importuser',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Dark Mode'),
        ),
        migrations.AlterField(
            model_name='importuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name'),
        ),
    ]
