# Generated by Django 3.0.3 on 2020-02-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0015_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='importuser',
            name='notifications',
            field=models.BooleanField(default=False, verbose_name='Notifications'),
        ),
    ]
