# Generated by Django 3.0.3 on 2020-02-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0016_importuser_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importuser',
            name='notifications',
            field=models.BooleanField(default=True, verbose_name='Notifications'),
        ),
    ]
